"""empty message

Revision ID: f6005b574ab3
Revises: 
Create Date: 2021-08-26 09:11:48.890657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6005b574ab3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminstration_storage_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_leave_requests', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_settings', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=30), nullable=False),
    sa.Column('_gender', sa.Boolean(), nullable=False),
    sa.Column('email_confirmation_code', sa.String(length=5), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin_data_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_data_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_data_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('nationality', sa.String(length=30), nullable=False),
    sa.Column('qualification', sa.String(length=35), nullable=False),
    sa.Column('major', sa.String(length=35), nullable=False),
    sa.Column('current_job', sa.String(length=50), nullable=False),
    sa.Column('_subjects', sa.String(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('_tools_used_for_online_tutoring', sa.String(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=130), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('min_students', sa.Integer(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('began', sa.Boolean(), nullable=False),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.Column('course_type', sa.Integer(), nullable=False),
    sa.Column('_period', sa.Integer(), nullable=True),
    sa.Column('_start_date', sa.DateTime(), nullable=True),
    sa.Column('_end_date', sa.DateTime(), nullable=True),
    sa.Column('links', sa.String(), nullable=False),
    sa.Column('weekly_time_table_json', sa.String(length=1000), nullable=False),
    sa.Column('_state', sa.String(), nullable=False),
    sa.Column('number_of_students_paid', sa.Integer(), nullable=False),
    sa.Column('have_sent_first_payment_emails', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('tutor_data_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_data_model_id'], ['tutor_data_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('course_model_id', sa.Integer(), nullable=False),
    sa.Column('student_data_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_model_id'], ['course_model.id'], ),
    sa.ForeignKeyConstraint(['student_data_model_id'], ['student_data_model.id'], ),
    sa.PrimaryKeyConstraint('course_model_id', 'student_data_model_id')
    )
    op.create_table('payment_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_transactions_object', sa.String(), nullable=False),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_model')
    op.drop_table('courses')
    op.drop_table('course_model')
    op.drop_table('tutor_data_model')
    op.drop_table('student_data_model')
    op.drop_table('admin_data_model')
    op.drop_table('user_model')
    op.drop_table('site_settings_model')
    op.drop_table('adminstration_storage_model')
    # ### end Alembic commands ###
